# Generated by Django 6.0.3 on 2026-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0002_carrera_tipo_alter_carrera_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('Tecnico', 'Técnico'), ('Tecnologo', 'Tecnólogo'), ('Curso', 'Curso Complementario')], default='Tecnico', max_length=20),
        ),
    ]
