# Generated by Django 6.0.3 on 2026-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_alter_carrera_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción profesional de la carrera'),
        ),
    ]
