# Generated by Django 6.0.2 on 2026-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('Tecnico', 'Técnico'), ('Tecnologo', 'Tecnólogo'), ('Curso', 'Curso Complementario')], default='Tecnico', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
